// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQ8kAkJgkAyshmb4VsTQZLKcHfdJoSf8',
    appId: '1:935458140153:web:6a04e3b4d7b8621e389728',
    messagingSenderId: '935458140153',
    projectId: 'sharedjourney-3ff2a',
    authDomain: 'sharedjourney-3ff2a.firebaseapp.com',
    storageBucket: 'sharedjourney-3ff2a.firebasestorage.app',
    measurementId: 'G-JPHP02LC5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CixN75wcNpd4JAIWUxl4CcRPrDErKaI',
    appId: '1:935458140153:android:bec3e0ada50f4a22389728',
    messagingSenderId: '935458140153',
    projectId: 'sharedjourney-3ff2a',
    storageBucket: 'sharedjourney-3ff2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5qWDuZf03tyAidt2Ka53nq-hnXYStqk',
    appId: '1:935458140153:ios:9effbae0acbab9fd389728',
    messagingSenderId: '935458140153',
    projectId: 'sharedjourney-3ff2a',
    storageBucket: 'sharedjourney-3ff2a.firebasestorage.app',
    iosBundleId: 'com.example.sharedgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5qWDuZf03tyAidt2Ka53nq-hnXYStqk',
    appId: '1:935458140153:ios:9effbae0acbab9fd389728',
    messagingSenderId: '935458140153',
    projectId: 'sharedjourney-3ff2a',
    storageBucket: 'sharedjourney-3ff2a.firebasestorage.app',
    iosBundleId: 'com.example.sharedgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmQ8kAkJgkAyshmb4VsTQZLKcHfdJoSf8',
    appId: '1:935458140153:web:2878865f9b4aec5f389728',
    messagingSenderId: '935458140153',
    projectId: 'sharedjourney-3ff2a',
    authDomain: 'sharedjourney-3ff2a.firebaseapp.com',
    storageBucket: 'sharedjourney-3ff2a.firebasestorage.app',
    measurementId: 'G-MJ3CJ3YSF9',
  );
}
